version: "3.9"

networks:
  ticketz:

volumes:
  postgres_data:
  redis_data:
  backend_public:
  backend_private:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - backend_public:/usr/src/app/public
      - backend_private:/usr/src/app/private
    env_file:
      - .env-backend-local
    restart: always
    depends_on:
      - postgres
      - redis
    # Exponer puerto 3000 backend en host (para NPM/api-ticketz.serx.cloud)
    ports:
      - "3000:3000"
    networks:
      - ticketz

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - CI=false
    env_file:
      - .env-frontend-local
    volumes:
      - backend_public:/var/www/backend-public
    restart: always
    depends_on:
      - backend
    # Exponer puerto 80 frontend en host (para NPM/ticketz.serx.cloud)
    ports:
      - "3001:80"
    networks:
      - ticketz

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ticketz}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
      - POSTGRES_DB=${POSTGRES_DB:-ticketz}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=${TZ:-America/Bogota}
    expose:
      - 5432
    restart: always
    networks:
      - ticketz

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - ticketz

  sidekick:
    image: ghcr.io/ticketz-oss/ticketz-sidekick:latest
    profiles: ["do-not-start"]
    env_file:
      - .env-backend-local
    restart: unless-stopped
    volumes:
      - backend_public:/backend-public
      - backend_private:/backend-private
      - ./backups:/backups
      - ./retrieve:/retrieve
    depends_on:
      - postgres
    networks:
      - ticketz

